config/routes.rb
Rails.application.routes.draw do
  root 'transactions#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :transactions, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  validates :amount, :sender, :receiver, presence: true

  after_create :trigger_transaction

  private

  def trigger_transaction
    TransactionBalanceService.new(self).process
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sent_transactions, class_name: "Transaction", foreign_key: "sender_id"
  has_many :received_transactions, class_name: "Transaction", foreign_key: "receiver_id"

  validates :full_name, :email, presence: true

  def to_s
    full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    @balance = current_user.balance
    @sent_transactions = current_user.sent_transactions
    @received_transactions = current_user.received_transactions
  end

  def new
    @users = User.all.reject{ |user| user == current_user }
  end

  def create
    transaction = Transaction.new(transaction_params.merge(sender_id: current_user.id))
    if transaction.save!
      flash[:notice] = "You transaction has been sent"
      redirect_to transactions_path
    else
      flash[:error] = "There was an error with your transaction"
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:amount, :receiver_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bambank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>

  <% if flash[:error] %>
    <%= flasgh[:error] %>
  <% end %>

  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<h1> Current Balance : <%= @balance %> </h1>

<%= link_to 'Send Bambeuros', new_transaction_path %>

<h2> Transactions Sent </h2>
<table>
  <tr>
    <th> Name </th>
    <th> Amount </th>
    <th> Balance before </th>
    <th> Balance after </th>
  </tr>
  <% @sent_transactions.each do |t| %>
    <tr>
      <td><%= t.receiver %></td>
      <td><%= t.amount %></td>
      <td><%= t.before_sender_balance %></td>
      <td><%= t.after_sender_balance %></td>
    </tr>
  <% end %>
</table>

<h2> Transactions Received </h2>
<table>
  <tr>
    <th> Name </th>
    <th> Amount </th>
    <th> Balance before </th>
    <th> Balance after </th>
  </tr>
  <% @received_transactions.each do |t| %>
    <tr>
      <td><%= t.sender %></td>
      <td><%= t.amount %></td>
      <td><%= t.before_receiver_balance %></td>
      <td><%= t.after_receiver_balance %></td>
    </tr>
  <% end %>
</table>

app/views/transactions/new.html.erb
<h1>New Transactions</h1>

<%= simple_form_for :transaction, url: transactions_path do |f| %>
  <%= f.input :amount %>
  <%= f.input :receiver_id, collection: @users, label_method: :full_name, value_method: :id, label: "Send to" %>
  <%= f.submit %>
<% end %>